set(ACCOUNTS_PREFIX_DIR ${CMAKE_INSTALL_PREFIX})
set(ACCOUNTS_PROVIDERS_DIR ${CMAKE_INSTALL_PREFIX}/share/accounts/providers)
set(ACCOUNTS_SERVICES_DIR ${CMAKE_INSTALL_PREFIX}/share/accounts/services)